language: node_js
node_js: '12'

install: 
  - npm install
script:
  - npm run bootstrap
  - npm run build
  - npm test

deploy:
  provider: releases
  api_key: ${GH_token}
  file_glob: true
  file: '*'
  skip_cleanup: true
  on:
    branch: main
    tags: true